### ISSUE TITLE
E185: Cannot find color scheme 'molokai'

### ISSUE THREAD

**Issue by aruzmeister** [fatih/dotfiles#1]
I think so source of repo is missing from your plugin list of vimrc file.

Error detected while processing /home/travis/.vimrc:
line  159:
E185: Cannot find color scheme 'molokai'
Press ENTER or type command to continue

E117: Unknown function: fugitive#statusline
E15: Invalid expression: fugitive#statusline()

**Comment by fatih** [comment]
Install https://github.com/fatih/molokai Thanks :)

**Comment by aruzmeister** [comment]
I have been following your vimrc file since past few months and after awhile when i again try to install in new linux machine yesterday, i am getting couples of error. Can u verify your source with it. I have uploaded some screenshot.

![github](https://cloud.githubusercontent.com/assets/2974077/7208283/40864ffc-e55d-11e4-9c10-12539f8d4e99.png)

![github2](https://cloud.githubusercontent.com/assets/2974077/7208288/4a329b6e-e55d-11e4-9c95-1000888c7beb.png)

**Comment by aruzmeister** [comment]
Also Molokai installed properly but never stop giving error.
line 159:
E185: Cannot find color scheme 'molokai'
Press ENTER or type command to continue

**Comment by timblackwell** [comment]
Hi @aruzmeister, I am having the same issue. Did you ever get molokai installed?
